# ASSIGNMENT CONFIG
solutions_pdf: true
export_cell:
    instructions: "These are some submission instructions."
generate: 
    pdf: true
    filtering: true
    pagebreaks: true
    zips: false

In [26]:
import otter
import pandas as pd
import numpy as np
%matplotlib inline
import otter
import matplotlib.pylab as plt
from datascience import *
grader = otter.Notebook()

<p><img alt="Colaborat" style="height: 220px;" src="https://github.com/fundatosudea/material_20242/blob/develop_otter/Imag/Logos/Escudo-UdeA.svg.png?raw=true" align="left" hspace="10px" vspace="0px"></p>

# Fundamentos en ciencias de datos


## Laboratorio 2: Operaciones con tablas

¡Bienvenidos al Laboratorio 2! Esta semana, aprenderemos cómo importar un módulo y prácticaremos operaciones con tablas. Algunas referencias estan dadas en el siguiente enlace [enlace](https://www.data8.org/fa23/reference/), el cual tiene información útil para este práctica de laboratorio.

**Lectura recomendada**:
  * [Introducción a las Tablas](https://www.inferentialthinking.com/chapters/03/4/Introduction_to_Tables)

Como recordatorio, estas son las políticas para obtener una nota completa:

1. Para los estudiantes inscritos en el <span style="color: #BC412B">**Laboratorio regular**</span> en persona, recibirán crédito de laboratorio al **asistir** a la sección de laboratorio y lograr un progreso significativo en ```notebook de jupyter```.



**Envío**: Una vez que haya terminado, ejecute todas las celdas además de la última, seleccione Archivo > Guardar cuaderno y luego ejecute la celda final. El resultado contendrá un archivo zip que podrá utilizar para enviarlo.

Comencemos configurando las pruebas e importaciones ejecutando la siguiente celda.

# 1. Revisión: Los componentes básicos del código Python

Los dos bloques de construcción del código Python son *expresiones* y *declaraciones*. Una **expresión** es un fragmento de código que:

-  Es autónomo, lo que significa que tendría sentido escribirlo en una línea por sí solo, y
-  generalmente se evalúa como un valor.


Aquí hay dos expresiones que se evalúan como 3:

     3
     5 - 2
    
Un tipo importante de expresión es : ```call expression``` en inglés o  **expresión de ejecución**. Una expresión de ejecución  se utilizan para describir la acción de llamar o invocar una función o método en programación,  comienza con el nombre de una función y va seguida de los argumentos de esa función entre paréntesis. La función devuelve algún valor, según sus argumentos. Algunas funciones matemáticas importantes se enumeran a continuación.

| Función | Descripción |
|----------|------------|
| `abs` | Devuelve el valor absoluto de su argumento |
| `max` | Devuelve el máximo de todos sus argumentos |
| `min` | Devuelve el mínimo de todos sus argumentos |
| `pow` | Eleva su primer argumento a la potencia de su segundo argumento |
| `round` | Redondea su argumento al entero más cercano |

Aquí hay dos expresiones de ejecución que se evalúan como 3:

     abs(2 - 5)
     max(round(2.8), min(pow(2, 10), -1 * pow(2, 10)))

La expresión `2 - 5` y las dos llamadas de ejecuciones  anteriores,  son ejemplos de **expresiones compuestas**, lo que significa que en realidad son combinaciones de varias expresiones más pequeñas. `2 - 5` combina las expresiones `2` y `5` mediante resta. En este caso, `2` y `5` se denominan **subexpresiones** porque son expresiones que forman parte de una expresión más grande.

Una **declaración** es una línea completa de código. Algunas declaraciones son sólo expresiones. Las expresiones enumeradas anteriormente son ejemplos.

Otras declaraciones *hacen que algo suceda* en lugar de *tener un valor*. Por ejemplo, una **declaración de asignación** asigna un valor a un nombre.

Una buena forma de pensar en esto es que estamos **evaluando el lado derecho** del signo igual y **asignándolo al lado izquierdo**. Aquí hay algunas declaraciones de asignación:
    
     altura = 1.3
     num_cinco = abs(-5)
     dif_altura_abs = abs(altura - 1.688)

Una idea importante en programación es que se pueden construir cosas grandes e interesantes combinando muchas cosas simples y poco interesantes. La clave para comprender un código complicado es **dividirlo en sus componentes simples**

Por ejemplo, suceden muchas operaciones en la última declaración como combinación operaciones más básicas. La siguiente  imagen describe mejor lo que está pasando (Notese que algunos nombres están en inglés,  para ir familiarizandose con algunos nombres que son de interés en python) 

<img src="https://github.com/fundatosudea/material_20242/blob/develop_otter/Imag/fig/fig_04expresiones.png?raw=true">

# BEGIN QUESTION
name: q11

**Pregunta 1.1.** En la siguiente celda, asigne el nombre `nuevo_año` al **número mayor** entre los dos números siguientes:

-  el **valor absoluto** de $2^{6}-2^{11}-2^{5} - 8$, y
-  $5 \times 13 \times 31 + 7$.

Intente utilizar solo una declaración (una línea de código). Asegúrese de verificar su trabajo ejecutando la celda de prueba después.

# BEGIN SOLUTION

In [27]:
# BEGIN SOLUTION NO PROMPT
nuevo_año = max (abs(2**6-2**11-2**5-8),    5*13*31+7)
# END SOLUTION

""" # BEGIN PROMPT
nuevo_año=...
""" # END PROMPT

' # BEGIN PROMPT\nnuevo_año=...\n'

# END SOLUTION

# BEGIN TESTS

In [28]:
assert (isinstance(nuevo_año, int))

In [29]:
import numpy as np
assert (np.isclose(nuevo_año,2024, rtol=1E-8))

# END TESTS

# END QUESTION

En el ejemplo anterior, creamos una sola línea de código porque solo involucra operaciones matemáticas. Sin embargo, las preguntas de programación más complicadas requerirán más pasos. No siempre es una buena idea agrupar estos pasos en una sola línea porque puede hacer que el código sea más difícil de leer y de depurar.

Una buena práctica de programación implica dividir el código en pasos más pequeños y utilizar nombres apropiados. ¡Tendrás mucha práctica en el resto de este curso!

# 2. Importación de código

La mayor parte de la programación implica un trabajo muy similar al trabajo que se ha realizado antes. Dado que escribir código lleva mucho tiempo, es bueno confiar en el código publicado por otros cuando sea posible. En lugar de copiar y pegar, Python nos permite **importar módulos**. Un módulo es un archivo con código Python que tiene variables y funciones definidas. Al importar un módulo, podemos usar su código en nuestro propio cuaderno.

Python incluye muchos módulos útiles que están a sólo una "importación" de distancia. Veremos el módulo "math" como primer ejemplo. El módulo "math" es extremadamente útil para calcular expresiones matemáticas en Python.

Supongamos que queremos calcular con mucha precisión el área de un círculo A con un radio R de 5 metros. Para eso, necesitamos la constante $\pi$, que es aproximadamente 3.14. Convenientemente, el módulo "math" tiene "pi" definido para nosotros. Ejecute la siguiente celda para importar el módulo matemático:

\begin{equation}
A = \pi R^2 = \pi 5^2\  \text{m}^2
\end{equation}

In [30]:
import math
radio = 5
area_del_circulo = radio**2 * math.pi
area_del_circulo

78.53981633974483

En el código anterior, la línea "import math" importa el módulo matemático. Esta declaración crea un módulo y luego asigna el nombre "math" a ese módulo. Ahora podemos acceder a cualquier variable o función definida en `math` escribiendo el nombre del módulo seguido de un punto, luego seguido del nombre de la variable o función que queremos.

     <nombre del módulo>.<nombre>

# BEGIN QUESTION
name: q21

**Pregunta 2.1.** El módulo `math` también proporciona el nombre `e` para la base del logaritmo natural, que es aproximadamente 2.71. Calcule $e^{\pi}-\pi$, dándole el nombre `cerca_veinte`.

*Recuerda: ¡También puedes acceder a `pi` desde el módulo `math`!*

# BEGIN SOLUTION

In [31]:
from math import *
# BEGIN SOLUTION NO PROMPT
cerca_veinte = e**math.pi-math.pi
# END SOLUTION
""" # BEGIN PROMPT
cerca_veinte=...
""" # END PROMPT
cerca_veinte

19.99909997918947

# END SOLUTION

# BEGIN TESTS

In [32]:
assert(isinstance(cerca_veinte, float))

In [33]:
import numpy as np
assert (np.isclose(cerca_veinte,19.999, rtol=1E-2))

# END TESTS

# END QUESTION

## 2.1. Accediendo a funciones

En la pregunta anterior, accedió a variables dentro del módulo "math".

**Los módulos** también definen **funciones**. Por ejemplo, "math" proporciona la función "floor" que se utiliza en programación para redondear un número hacia abajo al entero más cercano. Habiendo importado ya "math", podemos escribir "math.floor(7.5)" para calcular el `floor` de 7.5 que es 7.

**Pregunta 2.1.1.** Calcule el `floor` del número  $\pi$ usando el módulo `math`. Asigne al resultado el nombre `floor_de_pi`.

# BEGIN QUESTION
name: q211

# BEGIN SOLUTION

In [34]:
from math import *

# BEGIN SOLUTION NO PROMPT
floor_de_pi=floor(pi)

# END SOLUTION

""" # BEGIN PROMPT
floor_de_pi=...
""" # END PROMPT

floor_de_pi

3

# END SOLUTION

# BEGIN TESTS

In [35]:
assert(isinstance(floor_de_pi, int))

In [36]:
import numpy as np
assert(np.isclose(floor_de_pi,3, rtol=1E-8))

# END TESTS

# END QUESTION

Para que tengas como referencia, a continuación se muestran algunos ejemplos más de funciones del módulo "math".

Observe cómo diferentes funciones toman diferentes números de argumentos. A menudo, la [documentación](https://docs.python.org/3/library/math.html) del módulo proporcionará información sobre cuántos argumentos se requieren para cada función.

*Sugerencia: si presiona `shift+tab` mientras está al lado de la llamada de función, aparecerá la documentación para esa función.*

In [37]:
# Calcular logaritmos (el logaritmo de 8 en base 2).
# El resultado es 3 porque 2 elevado a 3 es 8.
math.log(8, 2)

3.0

In [38]:
# Calcular raíces cuadradas.
math.sqrt(5)

2.23606797749979

Hay varias formas de importar y acceder a código desde fuentes externas. El método que usamos anteriormente, `<importar>.<nombre_módulo>`, importa el módulo completo,  requiere que usemos `<nombre_módulo>.<nombre>` para acceder a su código.

También podemos importar una constante o función específica en lugar del módulo completo. Tenga en cuenta que no es necesario utilizar el nombre del módulo de antemano para hacer referencia a ese valor en particular. Sin embargo, debe tener cuidado al reasignar los nombres de las constantes o funciones a otros valores.

In [39]:
# Importando solo cos y pi desde matemáticas.
# No tenemos que usar "matemáticas" delante de cos o pi
from math import cos, pi
print(cos(pi))

# Sin embargo, tenemos que usarlo delante de otras funciones matemáticas.
math.log(pi)

-1.0

1.1447298858494002

O podemos importar cada función y valor de todo el módulo.

In [40]:
# Por último, podemos importar todo desde matemáticas usando el *
# Una vez más, no tenemos que usar "matemáticas". antemano
from math import *
log(pi)

1.1447298858494002

No se preocupe demasiado por qué tipo de importación utilizar. A menudo es una elección de estilo de codificación que queda en manos de cada programador. En este curso, siempre importará los módulos necesarios cuando ejecute la celda de configuración (como la primera celda de código en esta práctica de laboratorio).

¡Pasemos a practicar algunas de las operaciones en tablas que aprendiste en las clases!

# 3. Operaciones con tablas.

La tabla `farmers_markets.csv` contiene datos sobre los mercados de agricultores en los Estados Unidos (datos asociados con [el USDA](https://apps.ams.usda.gov/FarmersMarketsExport/ExcelExport.aspx)). Cada fila representa uno de esos mercados.

Ejecute la siguiente celda para cargar la tabla `farmers_markets`. No habrá resultados; no se espera ningún resultado ya que la celda contiene una declaración de asignación. Una declaración de asignación no produce ningún resultado (no produce ningún valor).

In [44]:
# Simplemente ejecuta esta celda
farmers_markets = Table.read_table('farmers_markets.csv')
farmers_markets

FMID    | MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime            | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
1012063 |  Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | 6/28/2016 12:10:09 PM | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1011871 |  Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | 4/9/2016 8:05:17 PM   | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1011878 | 100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | 4/16/2016 12:37:56 PM | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1009364 | 106 S. Main Street Farmers Market                | 106 S. Main Street                                       | Six Mile   | nan                  | South Carolina       | 29682 | -82.8187 | 34.8042 | http://thetownofsixmile.wordpress.com/                | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2013                  | nan                                                        | Y      | N    | N       | N     | N    | nan                      | nan                                          | nan         | nan         | nan         | nan         | nan         | nan
1010691 | 10th Steet Community Farmers Market              | 10th Street and Poplar                                   | Lamar      | Barton               | Missouri             | 64759 | -94.2746 | 37.4956 | nan                                                   | nan                                                          | nan                                 | nan     | http://agrimissouri.com/mo-grown/grodetail.php?type=mo-g ... | -       | N    | Y          | N      | Y      | N       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | N    | Y      | Y       | Y        | Y    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 10/28/2014 9:49:46 AM | nan                                                        | Y      | N    | N       | N     | N    | 04/02/2014 to 11/30/2014 | Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;   | nan         | nan         | nan         | nan         | nan         | nan
1002454 | 112st Madison Avenue                             | 112th Madison Avenue                                     | New York   | New York             | New York             | 10029 | -73.9493 | 40.7939 | nan                                                   | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | Y      | Y       | N    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | Y    | N      | N       | Y        | Y    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 3/1/2012 10:38:22 AM  | Private business parking lot                               | N      | N    | Y       | Y     | N    | July to November         | Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm; | nan         | nan         | nan         | nan         | nan         | nan
1011100 | 12 South Farmers Market                          | 3000 Granny White Pike                                   | Nashville  | Davidson             | Tennessee            | 37204 | -86.7907 | 36.1184 | http://www.12southfarmersmarket.com                   | 12_South_Farmers_Market                                      | @12southfrmsmkt                     | nan     | @12southfrmsmkt                                              | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | N    | Y      | N     | Y      | N      | Y      | Y         | Y       | N             | 5/1/2015 10:40:56 AM  | nan                                                        | Y      | N    | N       | N     | Y    | 05/05/2015 to 10/27/2015 | Tue: 3:30 PM-6:30 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1009845 | 125th Street Fresh Connect Farmers' Market       | 163 West 125th Street and Adam Clayton Powell, Jr. Blvd. | New York   | New York             | New York             | 10027 | -73.9482 | 40.809  | http://www.125thStreetFarmersMarket.com               | https://www.facebook.com/125thStreetFarmersMarket            | https://twitter.com/FarmMarket125th | nan     | Instagram--> 125thStreetFarmersMarket                        | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | Y      | N     | Y      | N      | Y      | N         | N       | N             | 4/7/2014 4:32:01 PM   | Federal/State government building grounds                  | Y      | Y    | N       | Y     | Y    | 06/10/2014 to 11/25/2014 | Tue: 10:00 AM-7:00 PM;                       | nan         | nan         | nan         | nan         | nan         | nan
1005586 | 12th & Brandywine Urban Farm Market              | 12th & Brandywine Streets                                | Wilmington | New Castle           | Delaware             | 19801 | -75.5345 | 39.7421 | nan                                                   | https://www.facebook.com/pages/12th-Brandywine-Urban-Far ... | nan                                 | nan     | https://www.facebook.com/delawareurbanfarmcoalition          | N       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 4/3/2014 3:43:31 PM   | On a farm from: a barn, a greenhouse, a tent, a stand, etc | N      | N    | N       | N     | Y    | 05/16/2014 to 10/17/2014 | Fri: 8:00 AM-11:00 AM;                       | nan         | nan         | nan         | nan         | nan         | nan
1008071 | 14&U Farmers' Market                             | 1400 U Street NW                                         | Washington | District of Columbia | District of Columbia | 20009 | -77.0321 | 38.917  | nan                                                   | https://www.facebook.com/14UFarmersMarket                    | https://twitter.com/14UFarmersMkt   | nan     | nan                                                          | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | N        | N    | N     | N    | N      | Y     | Y      | Y      | Y      | N         | N       | N             | 4/5/2014 1:49:04 PM   | Other                                                      | Y      | Y    | Y       | Y     | Y    | 05/03/2014 to 11/22/2014 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
... (8536 rows omitted)

Examinemos nuestra tabla para ver qué datos contiene.

**Pregunta 3.1.** Utilice el método `show` para mostrar las primeras 5 filas de `farmers_markets`.

*Nota:* Los términos "método" y "función" técnicamente no son lo mismo, pero para los propósitos de este curso, los usaremos indistintamente.

**Pista:** `tbl.show(3)` mostrará las primeras 3 filas de la tabla denominada `tbl`. Además, asegúrese de no llamar a `.show()` sin un argumento, ya que esto bloqueará su kernel.

In [ ]:
...

Observe que faltan algunos de los valores en esta tabla, como se indica con "nan". Esto significa que el valor no está disponible (por ejemplo, si no conocemos la dirección del mercado) o no es aplicable (por ejemplo, si el mercado no tiene una dirección). ¡También notarás que la tabla tiene una gran cantidad de columnas!

### `num_columnas`

La propiedad de la tabla `num_columns` devuelve el número de columnas de una tabla. (Una "propiedad" es solo un método al que no es necesario llamar agregando paréntesis).

Llamada de ejemplo: `tbl.num_columns` devolverá el número de columnas en una tabla llamada `tbl`

**Pregunta 3.2.** Utilice `num_columns` para encontrar el número de columnas en nuestro conjunto de datos de mercados de agricultores.

Asigne el número de columnas a `num_farmers_markets_columns`.

# BEGIN QUESTION
name: q32

# BEGIN SOLUTION

In [9]:
import numpy as np
from datascience import *

farmers_markets = Table.read_table('farmers_markets.csv')

# BEGIN SOLUTION NO PROMPT
num_farmers_markets_columns=farmers_markets.num_columns

# END SOLUTION

""" # BEGIN PROMPT
num_farmers_markets_columns= ...
print("The table has", num_farmers_markets_columns, "columns in it!")
""" # END PROMPT
num_farmers_markets_columns

59

# END SOLUTION

# BEGIN TESTS

In [8]:
isinstance(num_farmers_markets_columns, int)==True

True

In [10]:
import numpy as np
np.isclose(num_farmers_markets_columns,59, rtol=1E1)==True

True

# END TESTS

# END QUESTION

### `num_rows`

De manera similar, la propiedad `num_rows` te indica cuántas filas hay en una tabla.

In [ ]:
# Just run this cell

num_farmers_markets_rows = farmers_markets.num_rows
print("The table has", num_farmers_markets_rows, "rows in it!")

### `select`

La mayoría de las columnas tratan sobre productos concretos: si el mercado vende tofu, comida para mascotas, etc. Si no estamos interesados en esa información, la tabla resulta difícil de leer. Esto surge más de lo que se podría pensar, porque es posible que las personas que recopilan y publican datos no sepan de antemano qué querrán hacer con ellos.

En tales situaciones, podemos usar el método de tabla "seleccionar" para elegir solo las columnas que queremos en una tabla en particular. Se necesitan muchos argumentos. Cada uno debe ser el nombre de una columna de la tabla. Devuelve una nueva tabla con solo esas columnas. Las columnas están en el orden *en el que fueron enumeradas como argumentos*.

Por ejemplo, el valor de `farmers_markets.select("MarketName", "State")` es una tabla con solo el nombre y el estado de cada mercado de agricultores en `farmers_markets`.



**Pregunta 3.3.** Utilice `select` para crear una tabla con solo el nombre, ciudad, estado, latitud (`y`) y longitud (`x`) de cada mercado. Llame a esa nueva tabla "farmers_markets_locations".

*Sugerencia:* Asegúrese de ser exacto al usar nombres de columnas con `select`; ¡Compruebe dos veces las mayúsculas!

# BEGIN QUESTION
name: q33

# BEGIN SOLUTION

In [24]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_locations=farmers_markets.select('y','x') 

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_locations= ...
""" # END PROMPT
farmers_markets_locations

y       | x
44.411  | -72.1403
41.3751 | -81.7286
42.296  | -85.5749
34.8042 | -82.8187
37.4956 | -94.2746
40.7939 | -73.9493
36.1184 | -86.7907
40.809  | -73.9482
39.7421 | -75.5345
38.917  | -77.0321
... (8536 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [23]:
isinstance(farmers_markets_locations, tables.Table)==True

True

In [37]:
(farmers_markets is farmers_markets_locations)==False

True

# END TESTS

# END QUESTION

### `drop`

`drop` tiene el mismo propósito que `select`, pero elimina las columnas que usted proporciona en lugar de las que no proporciona. Al igual que "seleccionar", "soltar" devuelve una nueva tabla.

**Pregunta 3.4.** Supongamos que simplemente no desea las columnas `FMID` y `updateTime` en `farmers_markets`. Cree una tabla que sea una copia de `farmers_markets` pero que no incluya esas columnas. Llame a esa tabla "farmers_markets_ without_fmid".

# BEGIN QUESTION
name: q34

# BEGIN SOLUTION

In [38]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_without_fmid =farmers_markets.drop('FMID','updateTime') 

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_without_fmid = ...
""" # END PROMPT
farmers_markets_without_fmid

MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
 Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
 Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
106 S. Main Street Farmers Market                | 106 S. Main Street                                       | Six Mile   | nan                  | South Carolina       | 29682 | -82.8187 | 34.8042 | http://thetownofsixmile.wordpress.com/                | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | nan                      | nan                                          | nan         | nan         | nan         | nan         | nan         | nan
10th Steet Community Farmers Market              | 10th Street and Poplar                                   | Lamar      | Barton               | Missouri             | 64759 | -94.2746 | 37.4956 | nan                                                   | nan                                                          | nan                                 | nan     | http://agrimissouri.com/mo-grown/grodetail.php?type=mo-g ... | -       | N    | Y          | N      | Y      | N       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | N    | Y      | Y       | Y        | Y    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | 04/02/2014 to 11/30/2014 | Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;   | nan         | nan         | nan         | nan         | nan         | nan
112st Madison Avenue                             | 112th Madison Avenue                                     | New York   | New York             | New York             | 10029 | -73.9493 | 40.7939 | nan                                                   | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | Y      | Y       | N    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | Y    | N      | N       | Y        | Y    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | Private business parking lot                               | N      | N    | Y       | Y     | N    | July to November         | Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm; | nan         | nan         | nan         | nan         | nan         | nan
12 South Farmers Market                          | 3000 Granny White Pike                                   | Nashville  | Davidson             | Tennessee            | 37204 | -86.7907 | 36.1184 | http://www.12southfarmersmarket.com                   | 12_South_Farmers_Market                                      | @12southfrmsmkt                     | nan     | @12southfrmsmkt                                              | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | N    | Y      | N     | Y      | N      | Y      | Y         | Y       | N             | nan                                                        | Y      | N    | N       | N     | Y    | 05/05/2015 to 10/27/2015 | Tue: 3:30 PM-6:30 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
125th Street Fresh Connect Farmers' Market       | 163 West 125th Street and Adam Clayton Powell, Jr. Blvd. | New York   | New York             | New York             | 10027 | -73.9482 | 40.809  | http://www.125thStreetFarmersMarket.com               | https://www.facebook.com/125thStreetFarmersMarket            | https://twitter.com/FarmMarket125th | nan     | Instagram--> 125thStreetFarmersMarket                        | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | Y      | N     | Y      | N      | Y      | N         | N       | N             | Federal/State government building grounds                  | Y      | Y    | N       | Y     | Y    | 06/10/2014 to 11/25/2014 | Tue: 10:00 AM-7:00 PM;                       | nan         | nan         | nan         | nan         | nan         | nan
12th & Brandywine Urban Farm Market              | 12th & Brandywine Streets                                | Wilmington | New Castle           | Delaware             | 19801 | -75.5345 | 39.7421 | nan                                                   | https://www.facebook.com/pages/12th-Brandywine-Urban-Far ... | nan                                 | nan     | https://www.facebook.com/delawareurbanfarmcoalition          | N       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | On a farm from: a barn, a greenhouse, a tent, a stand, etc | N      | N    | N       | N     | Y    | 05/16/2014 to 10/17/2014 | Fri: 8:00 AM-11:00 AM;                       | nan         | nan         | nan         | nan         | nan         | nan
14&U Farmers' Market                             | 1400 U Street NW                                         | Washington | District of Columbia | District of Columbia | 20009 | -77.0321 | 38.917  | nan                                                   | https://www.facebook.com/14UFarmersMarket                    | https://twitter.com/14UFarmersMkt   | nan     | nan                                                          | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | N        | N    | N     | N    | N      | Y     | Y      | Y      | Y      | N         | N       | N             | Other                                                      | Y      | Y    | Y       | Y     | Y    | 05/03/2014 to 11/22/2014 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
... (8536 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [39]:
isinstance(farmers_markets_without_fmid, tables.Table)==True

True

In [40]:
(farmers_markets_without_fmid is farmers_markets_locations)==False

True

# END TESTS

# END QUESTION

Ahora supongamos que queremos responder algunas preguntas sobre los mercados de agricultores en Estados Unidos. Por ejemplo, ¿qué mercado(s) tiene la mayor longitud (dada por la columna "x")?

Para responder a esto, ordenaremos `farmers_markets_locations` por longitud.

In [ ]:
farmers_markets_locations.sort('x')

Vaya, eso no respondió nuestra pregunta porque ordenamos de menor a mayor longitud. Para ver las longitudes más grandes, tendremos que ordenar en orden inverso.

In [ ]:
farmers_markets_locations.sort('x', descending=True)

(The `descending=True` se llama *argumento opcional*. Tiene un valor predeterminado de `False`, por lo que cuando le dices explícitamente a la función `descending=True`, la función ordenará en orden descendente).

### `sort`

Algunos detalles sobre la clasificación:

1. El primer argumento para "ordenar" es el nombre de una columna por la que ordenar.
2. Si la columna tiene texto, "ordenar" ordenará alfabéticamente; si la columna tiene números, se ordenará numéricamente, ambos en orden ascendente de forma predeterminada.
3. El valor de `farmers_markets_locations.sort("x")` es una *copia* de `farmers_markets_locations`; la tabla `farmers_markets_locations` no se modifica. Por ejemplo, si llamamos a `farmers_markets_locations.sort("x")`, ejecutar `farmers_markets_locations` por sí solo aún devolvería la tabla sin clasificar.
4. Las filas siempre permanecen juntas cuando se ordena una tabla. No tendría sentido ordenar solo una columna y dejar las otras columnas como están. Por ejemplo, en este caso, si ordenáramos solo la columna "x", todos los mercados de agricultores terminarían con las longitudes incorrectas.

**Pregunta 3.5.** Cree una versión de `farmers_markets_locations` que esté ordenada por **latitud (`y`)**, con las latitudes más grandes primero. Llámelo "farmers_markets_locations_by_latitude".

# BEGIN QUESTION
name: q35

# BEGIN SOLUTION

In [59]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_locations=farmers_markets.select('y','x') 
farmers_markets_locations_by_latitude=farmers_markets_locations.drop('x') 
farmers_markets_locations_by_latitude=farmers_markets_locations_by_latitude.sort('y')

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_locations_by_latitude= ...
""" # END PROMPT

farmers_markets_locations_by_latitude

y
17.7099
17.7322
17.7449
17.9686
17.9723
17.9782
17.9792
17.9854
18.0069
18.0089
... (8536 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [60]:
isinstance(farmers_markets_locations_by_latitude, tables.Table)==True

True

In [61]:
(farmers_markets_without_fmid is farmers_markets_locations)==False

True

In [65]:
np.isclose(farmers_markets_locations_by_latitude.num_columns,1, rtol=1E3)==True

True

In [78]:
farmers_markets_locations_by_latitude[0][0]<farmers_markets_locations_by_latitude[0][1]

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q36

Ahora digamos que queremos una tabla de todos los mercados de agricultores de California. La clasificación no nos ayudará mucho aquí porque California está más cerca del centro del conjunto de datos.

En su lugar, utilizamos el método de la tabla. `where`.

In [ ]:
california_farmers_markets = farmers_markets_locations.where('State', are.equal_to('California'))
california_farmers_markets

Ignora la sintaxis por el momento. En su lugar, intenta leer esa línea así:

> Asigne el nombre **`california_farmers_markets`** a una tabla cuyas filas son las filas de la tabla **`farmers_markets_locations`** **`donde`** están los **`"Estados"`** **` are equal to` `"California"`**.

### `where`

Ahora profundicemos un poco más en los detalles. `where` toma 2 argumentos:

1. El nombre de una columna. `where` busca filas donde los valores de esa columna cumplen algún criterio.
2. Un predicado que describe el criterio que debe cumplir la columna.

El predicado en el ejemplo anterior llamó a la función `are.equal_to` con el valor que queríamos, 'California'. Pronto veremos otros predicados.

`where` devuelve una tabla que es una copia de la tabla original, pero **con solo las filas que cumplen el predicado dado**.

**Pregunta 3.6.** Utilice `california_farmers_markets` para crear una tabla llamada `berkeley_markets` que contenga los mercados de agricultores en Berkeley, California.

# BEGIN SOLUTION

In [84]:
import numpy as np
from datascience import *

farmers_markets = Table.read_table('farmers_markets.csv')

# BEGIN SOLUTION NO PROMPT
berkeley_markets=farmers_markets.where('State', are.equal_to('California'))

# END SOLUTION

""" # BEGIN PROMPT
berkeley_markets= ...
""" # END PROMPT

berkeley_markets

FMID    | MarketName                               | street                      | city         | County         | State      | zip   | x        | y       | Website                                                 | Facebook                                       | Twitter                         | Youtube | OtherMedia                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime            | Location                          | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                | Season2Date              | Season2Time           | Season3Date              | Season3Time           | Season4Date | Season4Time
1005272 | Adelanto Stadium Farmers Market          | Hwy 395 & Rancho Drive      | Victorville  | San Bernardino | California | 92392 | -117.405 | 34.5593 | nan                                                     | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                        | nan                      | nan                   | nan                      | nan                   | nan         | nan
1009019 | Alameda Farmers' Market                  | Haight and Webster St.      | Alameda      | Alameda        | California | nan   | -122.277 | 37.7742 | http://www.pcfma.com                                    | https://www.facebook.com/AlamedaFarmersMarket  | nan                             | nan     | nan                          | Y       | N    | Y          | N      | N      | Y       | Y    | Y       | Y     | Y          | Y     | N    | N     | N    | N       | Y    | N      | Y       | Y        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 6/27/2016 12:57:44 PM | nan                               | Y      | Y    | N       | N     | N    | 01/01/2013 to 12/31/2013 | Tue: 9:00 AM-1:00 PM;Sat: 9:00 AM-1:00 PM; | nan                      | nan                   | nan                      | nan                   | nan         | nan
1008835 | Alisal Certified Farmers' Market         | 632 East Alisal Street      | Salinas      | Monterey       | California | 93905 | -121.634 | 36.6733 | http://www.everyonesharvest.org                         | https://www.facebook.com/EveryonesHarvest      | nan                             | nan     | nan                          | Y       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | Y     | N    | N     | N    | N       | N    | N      | N       | Y        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 6/27/2016 3:24:13 PM  | nan                               | Y      | Y    | Y       | Y     | Y    | 06/28/2016 to 10/11/2016 | Tue: 11:00 AM-4:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1009998 | Altadena Farmers' Market                 | 600 W. Palm Street          | Altadena     | Los Angeles    | California | 91001 | -118.158 | 34.2004 | http://www.altadenafarmersmarket.com                    | https://www.facebook.com/AltadenaFarmersMarket | https://twitter.com/AltadenaFM  | nan     | http://altadenafm.tumblr.com | Y       | N    | Y          | Y      | Y      | Y       | Y    | Y       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | N      | Y       | Y        | Y    | Y     | N    | Y      | N     | Y      | Y      | Y      | Y         | N       | N             | 4/22/2014 1:29:47 PM  | Local government building grounds | Y      | Y    | N       | Y     | Y    | 01/08/2014 to 03/05/2014 | Wed: 3:00 PM-7:00 PM;                      | 03/12/2014 to 11/05/2014 | Wed: 4:00 PM-8:00 PM; | 11/12/2014 to 12/31/2014 | Wed: 3:00 PM-7:00 PM; | nan         | nan
1011421 | Alum Rock Village Farmers' Market        | 57 North White Road         | San Jose     | Santa Clara    | California | nan   | -121.833 | 37.3678 | http://www.pcfma.org                                    | www.facebook.com/AlumRockVillageFarmersMarket  | www.twitter.com/PacCoastFarmers | nan     | nan                          | Y       | N    | N          | N      | N      | Y       | N    | Y       | N     | Y          | Y     | N    | N     | Y    | N       | Y    | N      | Y       | Y        | N    | Y     | N    | Y      | N     | Y      | N      | N      | N         | N       | N             | 7/20/2015 12:39:04 PM | nan                               | Y      | Y    | N       | N     | Y    | 01/01/2015 to 12/31/2015 | Sun: 8:00 AM-1:00 PM;                      | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005644 | Amador Farmers' Market-- Jackson         | Jackson Library/ True Value | Jackson      | Amador         | California | 95642 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | Y       | Y    | N       | Y     | Y          | N     | Y    | N     | N    | N       | Y    | N      | N       | N        | Y    | N     | N    | N      | Y     | Y      | N      | N      | N         | Y       | N             | 3/27/2015 6:09:06 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/07/2015 to 10/01/2015 | Sun: 9:00 AM-12:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005645 | Amador Farmers' Market-- Pine Grove      | Hwy 88 at Irishtown Rd.     | Pine Grove   | Amador         | California | 95665 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | Y          | N      | Y      | N       | Y    | N       | N     | Y          | Y     | Y    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | Y     | Y      | N      | N      | N         | Y       | N             | 3/27/2015 5:51:19 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/03/2015 to 10/01/2015 | Wed: 3:00 PM-6:00 PM;                      | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005646 | Amador Farmers' Market-- Sutter Creek    | Eureka St. & Highway 49     | Sutter Creek | Amador         | California | 95685 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | N     | Y          | Y     | Y    | N     | N    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | Y     | Y      | N      | N      | N         | N       | N             | 3/27/2015 5:50:12 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/13/2015 to 10/01/2015 | Sat: 9:00 AM-12:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1002089 | Anderson Happy Valley Farmers Market     | Happy Valley Rd.            | Anderson     | Shasta         | California | 96007 | -122.408 | 40.4487 | nan                                                     | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                        | nan                      | nan                   | nan                      | nan                   | nan         | nan
1006268 | Angels Camp Farmers Market-Fresh Fridays | Utica Park, Utica Lane      | Angels Camp  | Calaveras      | California | 95222 | -120.543 | 38.0722 | http://www.angelscampbusiness.com/events/fresh-fridays/ | nan                                            | nan                             | nan     | nan                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | N     | Y    | N     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | N      | N      | N      | N         | N       | N             | 5/1/2012 11:19:26 AM  | Other                             | N      | Y    | N       | Y     | N    | June to October          | Fri:5:00 PM - 8:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
... (745 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [85]:
isinstance(berkeley_markets, tables.Table)==True

True

In [86]:
(berkeley_markets is farmers_markets_locations)==False

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q41

Hasta ahora solo hemos estado usando `dónde` con el predicado que requiere encontrar que los valores en una columna sean *exactamente* iguales a un cierto valor. Sin embargo, hay muchos otros predicados. Hemos enumerado algunos de los más comunes a continuación, pero si desea una lista más completa, consulte la sección de predicados en la [hoja de referencia de Python] (https://www.data8.org/fa23/reference/#tablewhere-predicates).

|Predicate|Example|Result|
|-|-|-|
|`are.equal_to`|`are.equal_to(50)`|Find rows with values equal to 50|
|`are.not_equal_to`|`are.not_equal_to(50)`|Find rows with values not equal to 50|
|`are.above`|`are.above(50)`|Find rows with values above (and not equal to) 50|
|`are.above_or_equal_to`|`are.above_or_equal_to(50)`|Find rows with values above 50 or equal to 50|
|`are.below`|`are.below(50)`|Find rows with values below 50|
|`are.between`|`are.between(2, 10)`|Find rows with values above or equal to 2 and below 10|
|`are.between_or_equal_to`|`are.between_or_equal_to(2, 10)`|Find rows with values above or equal to 2 and below or equal to 10|

## 4. Analizando un conjunto de datos

Ahora que está familiarizado con las operaciones de tablas, ¡respondamos una pregunta interesante sobre un conjunto de datos!

Ejecute la siguiente celda para cargar la tabla `imdb`. Contiene información sobre las 250 películas mejor calificadas en IMDb.

In [ ]:
# Simplemente ejecuta esta celda

imdb = Table.read_table('imdb.csv')
imdb

A menudo, queremos realizar múltiples operaciones (clasificar, filtrar u otras) para convertir una tabla que tenemos en algo más útil. Puede realizar estas operaciones una por una, por ejemplo.

```
first_step = original_tbl.where(“col1”, are.equal_to(12))
second_step = first_step.sort(‘col2’, descending=True)
```
Sin embargo, dado que el valor de la expresión `original_tbl.where(“col1”, are.equal_to(12))` es en sí mismo una tabla, puedes simplemente llamar a un método de tabla en él:
```
original_tbl.where(“col1”, are.equal_to(12)).sort(‘col2’, descending=True)
```
Debe organizar su trabajo de la manera que tenga más sentido para usted, utilizando nombres informativos para las tablas intermedias que cree.

**Pregunta 4.1.** Cree una tabla de películas estrenadas entre 2010 y 2015 (inclusive) con calificaciones superiores a 8. La tabla solo debe contener las columnas `Title` and `Rating`, **en ese orden**.

Asigne la tabla al nombre `above_eight`.

*Pista:* Piensa en los pasos que debes seguir e intenta ordenarlos en un orden que tenga sentido. ¡Siéntete libre de crear tablas intermedias para cada paso, pero asegúrate de asignar a tu tabla final el nombre "above_eight"!

# BEGIN SOLUTION

In [ ]:
import numpy as np
from datascience import *

imdb = Table.read_table('imdb.csv')

# BEGIN SOLUTION NO PROMPT
above_eigh=imdb.where('Rating',are.above_or_equal_to(8)).where('Year',are.between_or_equal_to(2010, 2015))

# END SOLUTION

""" # BEGIN PROMPT
above_eigh= ...
""" # END PROMPT

above_eigh

# END SOLUTION

# BEGIN TESTS

In [ ]:
isinstance(berkeley_markets, tables.Table)==True

In [98]:
(above_eigh is imdb)==False

True

In [100]:
np.isclose(above_eigh.num_columns,5, rtol=1E3)==True

True

In [103]:
np.isclose(above_eigh.num_rows,29, rtol=1E3)==True

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q42

**Pregunta 4.2.** Utilice `num_rows` (y aritmética) para encontrar la *el numero* de películas en el conjunto de datos que se estrenaron entre 1900 y 1999, y la *el numero* de películas en el conjunto de datos que se estrenaron en el año 2000 o después.

Asigne "num_en_siglo_20" a el número de películas en el conjunto de datos que se estrenaron entre 1900 y 1999, y "num_en_siglo_21" a el número de películas en el conjunto de datos que se estrenaron en el año 2000 o después.

*Pista:* El *número* de películas estrenadas en el siglo XX es el *número* de películas estrenadas en el siglo XX, dividida por el *número total* de películas.

# BEGIN SOLUTION

In [1]:
import numpy as np
from datascience import *

imdb = Table.read_table('imdb.csv')

# BEGIN SOLUTION NO PROMPT

num_movies_in_dataset=imdb.num_rows
num_in_siglo_20=imdb.where('Year',are.between_or_equal_to(1900, 1999))
num_in_21st_century=imdb.where('Year',are.above_or_equal_to(2000))

proportion_in_20th_century=num_in_siglo_20.num_rows/num_movies_in_dataset
proportion_in_21st_century=num_in_21st_century.num_rows/num_movies_in_dataset

# END SOLUTION

""" # BEGIN PROMPT
num_movies_in_dataset = ...
num_in_20th_century = ...
num_in_21st_century = ...
proportion_in_20th_century = ...
proportion_in_21st_century = ...
""" # END PROMPT

proportion_in_20th_century
#proportion_in_21st_century

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

0.684

# END SOLUTION

# BEGIN TESTS

In [2]:
isinstance(proportion_in_20th_century, float)==True

True

In [3]:
isinstance(proportion_in_21st_century, float)==True

True

In [4]:
np.isclose(proportion_in_20th_century,0.7, rtol=1E-1)==True

True

In [6]:
np.isclose(proportion_in_21st_century,0.3, rtol=1E-1)==True

True

# END TESTS

# END QUESTION

## 5. Resumen

Para su referencia, aquí hay una tabla de todas las funciones y métodos que vimos en esta práctica de laboratorio. ¡Aprenderemos más métodos para agregar a esta tabla la próxima semana!

|Nombre|Ejemplo|Propósito|
|-|-|-|
|`sort`|`tbl.sort("N")`|Crear una copia de una tabla ordenada por los valores de una columna|
|`where`|`tbl.where("N", are.above(2))`|Crea una copia de una tabla con solo las filas que coinciden con algún *predicado*|
|`num_rows`|`tbl.num_rows`|Calcular el número de filas en una tabla|
|`num_columns`|`tbl.num_columns`|Calcular el número de columnas en una tabla|
|`select`|`tbl.select("N")`|Crear una copia de una tabla con solo algunas de las columnas|
|`drop`|`tbl.drop("N")`|Crear una copia de una tabla sin algunas de las columnas|

**¡Lego** quiere felicitarte por terminar el Laboratorio 2!

<img src="https://github.com/darioblandon/materials-fa23/blob/main/lab/lab02/lego.png?raw=1" alt="Picture of brown cavalier poodle dog" width="300"/>


---

¡Terminaste con el laboratorio!

**Información importante sobre el envío:**
- **Ejecuta todas las pruebas** y verifica que todas pasan
- **Guardar** desde el menú **Archivo**
- **Ejecute la celda final para generar el archivo zip**
- **Haga clic en el enlace para descargar el archivo zip**
- Luego, ve a [Gradescope](https://www.gradescope.com/courses/576157) y envía el archivo zip a la tarea correspondiente. El nombre de esta tarea es "Lab XX Autograder", donde XX es el número de laboratorio: 01, 02, 03, etc.

- Si terminas temprano en el laboratorio regular, **pídele a uno de los miembros del personal que te marque**.

**Es su responsabilidad asegurarse de que su trabajo esté guardado antes de ejecutar la última celda.**

## Envío

Asegúrese de haber ejecutado todas las celdas de su cuaderno en orden antes de ejecutar la siguiente celda, para que todas las imágenes/gráficos aparezcan en el resultado. La siguiente celda generará un archivo zip para que lo envíe. **¡Guarde antes de exportar!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)