In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook("lab2.ipynb")

In [ ]:
import otter
import pandas as pd
import numpy as np
%matplotlib inline
import otter
import matplotlib.pylab as plt
grader = otter.Notebook()

**Pregunta 1.1.** En la siguiente celda, asigne el nombre `new_year` al **número mayor** entre los dos números siguientes:

* el **valor absoluto** de $2^{6}-2^{11}-2^{5} - 7$, y
* $5 \times 13 \times 31 + 7$.

Intente utilizar solo una declaración (una línea de código). Asegúrese de verificar su trabajo ejecutando la celda de prueba después.

In [ ]:
# BEGIN SOLUTION NO PROMPT
new_year=abs(2**6-2**11-2**5-7)
# END SOLUTION

""" # BEGIN PROMPT
new_year=...
""" # END PROMPT

In [ ]:
grader.check("q11")

**Pregunta 2.1.** El módulo `math` también proporciona el nombre `e` para la base del logaritmo natural, que es aproximadamente 2,71. Calcule $e^{\pi}-\pi$, dándole el nombre `near_twenty`.

*Recuerda: ¡También puedes acceder a `pi` desde el módulo `math`!*

In [1]:
from math import *

# BEGIN SOLUTION NO PROMPT
near_twenty = e**pi-pi
# END SOLUTION

""" # BEGIN PROMPT
near_twenty=...
""" # END PROMPT


near_twenty

19.99909997918947

In [ ]:
grader.check("q21")

**Pregunta 2.1.1.** Calcule el piso de pi usando `floor` y `pi` del módulo `math`. Asigne al resultado el nombre `floor_of_pi`.

In [4]:
from math import *

# BEGIN SOLUTION NO PROMPT
floor_of_pi=floor(pi)

# END SOLUTION

""" # BEGIN PROMPT
floor_of_pi=...
""" # END PROMPT

floor_of_pi

3

In [ ]:
grader.check("q211")

**Pregunta 3.2.** Utilice `num_columns` para encontrar el número de columnas en nuestro conjunto de datos de mercados de agricultores.

Asigne el número de columnas a `num_farmers_markets_columns`.

In [9]:
import numpy as np
from datascience import *

farmers_markets = Table.read_table('farmers_markets.csv')

# BEGIN SOLUTION NO PROMPT
num_farmers_markets_columns=farmers_markets.num_columns

# END SOLUTION

""" # BEGIN PROMPT
num_farmers_markets_columns= ...
""" # END PROMPT
num_farmers_markets_columns

59

In [ ]:
grader.check("q32")

**Pregunta 3.3.** Utilice `select` para crear una tabla con solo el nombre, ciudad, estado, latitud (`y`) y longitud (`x`) de cada mercado. Llame a esa nueva tabla "farmers_markets_locations".

*Sugerencia:* Asegúrese de ser exacto al usar nombres de columnas con `select`; ¡Compruebe dos veces las mayúsculas!

In [24]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_locations=farmers_markets.select('y','x') 

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_locations= ...
""" # END PROMPT
farmers_markets_locations

y       | x
44.411  | -72.1403
41.3751 | -81.7286
42.296  | -85.5749
34.8042 | -82.8187
37.4956 | -94.2746
40.7939 | -73.9493
36.1184 | -86.7907
40.809  | -73.9482
39.7421 | -75.5345
38.917  | -77.0321
... (8536 rows omitted)

In [ ]:
grader.check("q33")

**Pregunta 3.4.** Supongamos que simplemente no desea las columnas `FMID` y `updateTime` en `farmers_markets`. Cree una tabla que sea una copia de `farmers_markets` pero que no incluya esas columnas. Llame a esa tabla "farmers_markets_ without_fmid".

In [38]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_without_fmid =farmers_markets.drop('FMID','updateTime') 

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_without_fmid = ...
""" # END PROMPT
farmers_markets_without_fmid

MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
 Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
 Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
106 S. Main Street Farmers Market                | 106 S. Main Street                                       | Six Mile   | nan                  | South Carolina       | 29682 | -82.8187 | 34.8042 | http://thetownofsixmile.wordpress.com/                | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | nan                      | nan                                          | nan         | nan         | nan         | nan         | nan         | nan
10th Steet Community Farmers Market              | 10th Street and Poplar                                   | Lamar      | Barton               | Missouri             | 64759 | -94.2746 | 37.4956 | nan                                                   | nan                                                          | nan                                 | nan     | http://agrimissouri.com/mo-grown/grodetail.php?type=mo-g ... | -       | N    | Y          | N      | Y      | N       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | N    | Y      | Y       | Y        | Y    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | 04/02/2014 to 11/30/2014 | Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;   | nan         | nan         | nan         | nan         | nan         | nan
112st Madison Avenue                             | 112th Madison Avenue                                     | New York   | New York             | New York             | 10029 | -73.9493 | 40.7939 | nan                                                   | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | Y      | Y       | N    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | Y    | N      | N       | Y        | Y    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | Private business parking lot                               | N      | N    | Y       | Y     | N    | July to November         | Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm; | nan         | nan         | nan         | nan         | nan         | nan
12 South Farmers Market                          | 3000 Granny White Pike                                   | Nashville  | Davidson             | Tennessee            | 37204 | -86.7907 | 36.1184 | http://www.12southfarmersmarket.com                   | 12_South_Farmers_Market                                      | @12southfrmsmkt                     | nan     | @12southfrmsmkt                                              | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | N    | Y      | N     | Y      | N      | Y      | Y         | Y       | N             | nan                                                        | Y      | N    | N       | N     | Y    | 05/05/2015 to 10/27/2015 | Tue: 3:30 PM-6:30 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
125th Street Fresh Connect Farmers' Market       | 163 West 125th Street and Adam Clayton Powell, Jr. Blvd. | New York   | New York             | New York             | 10027 | -73.9482 | 40.809  | http://www.125thStreetFarmersMarket.com               | https://www.facebook.com/125thStreetFarmersMarket            | https://twitter.com/FarmMarket125th | nan     | Instagram--> 125thStreetFarmersMarket                        | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | Y      | N     | Y      | N      | Y      | N         | N       | N             | Federal/State government building grounds                  | Y      | Y    | N       | Y     | Y    | 06/10/2014 to 11/25/2014 | Tue: 10:00 AM-7:00 PM;                       | nan         | nan         | nan         | nan         | nan         | nan
12th & Brandywine Urban Farm Market              | 12th & Brandywine Streets                                | Wilmington | New Castle           | Delaware             | 19801 | -75.5345 | 39.7421 | nan                                                   | https://www.facebook.com/pages/12th-Brandywine-Urban-Far ... | nan                                 | nan     | https://www.facebook.com/delawareurbanfarmcoalition          | N       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | On a farm from: a barn, a greenhouse, a tent, a stand, etc | N      | N    | N       | N     | Y    | 05/16/2014 to 10/17/2014 | Fri: 8:00 AM-11:00 AM;                       | nan         | nan         | nan         | nan         | nan         | nan
14&U Farmers' Market                             | 1400 U Street NW                                         | Washington | District of Columbia | District of Columbia | 20009 | -77.0321 | 38.917  | nan                                                   | https://www.facebook.com/14UFarmersMarket                    | https://twitter.com/14UFarmersMkt   | nan     | nan                                                          | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | N        | N    | N     | N    | N      | Y     | Y      | Y      | Y      | N         | N       | N             | Other                                                      | Y      | Y    | Y       | Y     | Y    | 05/03/2014 to 11/22/2014 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
... (8536 rows omitted)

In [ ]:
grader.check("q34")

**Pregunta 3.5.** Cree una versión de `farmers_markets_locations` que esté ordenada por **latitud (`y`)**, con las latitudes más grandes primero. Llámelo "farmers_markets_locations_by_latitude".

In [59]:
import numpy as np
from datascience import *
farmers_markets = Table.read_table('farmers_markets.csv')


# BEGIN SOLUTION NO PROMPT
farmers_markets_locations=farmers_markets.select('y','x') 
farmers_markets_locations_by_latitude=farmers_markets_locations.drop('x') 
farmers_markets_locations_by_latitude=farmers_markets_locations_by_latitude.sort('y')

# END SOLUTION

""" # BEGIN PROMPT
farmers_markets_locations_by_latitude= ...
""" # END PROMPT

farmers_markets_locations_by_latitude

y
17.7099
17.7322
17.7449
17.9686
17.9723
17.9782
17.9792
17.9854
18.0069
18.0089
... (8536 rows omitted)

In [ ]:
grader.check("q35")

**Pregunta 3.6.** Utilice `california_farmers_markets` para crear una tabla llamada `berkeley_markets` que contenga los mercados de agricultores en Berkeley, California.

In [84]:
import numpy as np
from datascience import *

farmers_markets = Table.read_table('farmers_markets.csv')

# BEGIN SOLUTION NO PROMPT
berkeley_markets=farmers_markets.where('State', are.equal_to('California'))

# END SOLUTION

""" # BEGIN PROMPT
berkeley_markets= ...
""" # END PROMPT

berkeley_markets

FMID    | MarketName                               | street                      | city         | County         | State      | zip   | x        | y       | Website                                                 | Facebook                                       | Twitter                         | Youtube | OtherMedia                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime            | Location                          | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                | Season2Date              | Season2Time           | Season3Date              | Season3Time           | Season4Date | Season4Time
1005272 | Adelanto Stadium Farmers Market          | Hwy 395 & Rancho Drive      | Victorville  | San Bernardino | California | 92392 | -117.405 | 34.5593 | nan                                                     | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                        | nan                      | nan                   | nan                      | nan                   | nan         | nan
1009019 | Alameda Farmers' Market                  | Haight and Webster St.      | Alameda      | Alameda        | California | nan   | -122.277 | 37.7742 | http://www.pcfma.com                                    | https://www.facebook.com/AlamedaFarmersMarket  | nan                             | nan     | nan                          | Y       | N    | Y          | N      | N      | Y       | Y    | Y       | Y     | Y          | Y     | N    | N     | N    | N       | Y    | N      | Y       | Y        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 6/27/2016 12:57:44 PM | nan                               | Y      | Y    | N       | N     | N    | 01/01/2013 to 12/31/2013 | Tue: 9:00 AM-1:00 PM;Sat: 9:00 AM-1:00 PM; | nan                      | nan                   | nan                      | nan                   | nan         | nan
1008835 | Alisal Certified Farmers' Market         | 632 East Alisal Street      | Salinas      | Monterey       | California | 93905 | -121.634 | 36.6733 | http://www.everyonesharvest.org                         | https://www.facebook.com/EveryonesHarvest      | nan                             | nan     | nan                          | Y       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | Y     | N    | N     | N    | N       | N    | N      | N       | Y        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | 6/27/2016 3:24:13 PM  | nan                               | Y      | Y    | Y       | Y     | Y    | 06/28/2016 to 10/11/2016 | Tue: 11:00 AM-4:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1009998 | Altadena Farmers' Market                 | 600 W. Palm Street          | Altadena     | Los Angeles    | California | 91001 | -118.158 | 34.2004 | http://www.altadenafarmersmarket.com                    | https://www.facebook.com/AltadenaFarmersMarket | https://twitter.com/AltadenaFM  | nan     | http://altadenafm.tumblr.com | Y       | N    | Y          | Y      | Y      | Y       | Y    | Y       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | N      | Y       | Y        | Y    | Y     | N    | Y      | N     | Y      | Y      | Y      | Y         | N       | N             | 4/22/2014 1:29:47 PM  | Local government building grounds | Y      | Y    | N       | Y     | Y    | 01/08/2014 to 03/05/2014 | Wed: 3:00 PM-7:00 PM;                      | 03/12/2014 to 11/05/2014 | Wed: 4:00 PM-8:00 PM; | 11/12/2014 to 12/31/2014 | Wed: 3:00 PM-7:00 PM; | nan         | nan
1011421 | Alum Rock Village Farmers' Market        | 57 North White Road         | San Jose     | Santa Clara    | California | nan   | -121.833 | 37.3678 | http://www.pcfma.org                                    | www.facebook.com/AlumRockVillageFarmersMarket  | www.twitter.com/PacCoastFarmers | nan     | nan                          | Y       | N    | N          | N      | N      | Y       | N    | Y       | N     | Y          | Y     | N    | N     | Y    | N       | Y    | N      | Y       | Y        | N    | Y     | N    | Y      | N     | Y      | N      | N      | N         | N       | N             | 7/20/2015 12:39:04 PM | nan                               | Y      | Y    | N       | N     | Y    | 01/01/2015 to 12/31/2015 | Sun: 8:00 AM-1:00 PM;                      | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005644 | Amador Farmers' Market-- Jackson         | Jackson Library/ True Value | Jackson      | Amador         | California | 95642 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | Y       | Y    | N       | Y     | Y          | N     | Y    | N     | N    | N       | Y    | N      | N       | N        | Y    | N     | N    | N      | Y     | Y      | N      | N      | N         | Y       | N             | 3/27/2015 6:09:06 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/07/2015 to 10/01/2015 | Sun: 9:00 AM-12:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005645 | Amador Farmers' Market-- Pine Grove      | Hwy 88 at Irishtown Rd.     | Pine Grove   | Amador         | California | 95665 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | Y          | N      | Y      | N       | Y    | N       | N     | Y          | Y     | Y    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | Y     | Y      | N      | N      | N         | Y       | N             | 3/27/2015 5:51:19 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/03/2015 to 10/01/2015 | Wed: 3:00 PM-6:00 PM;                      | nan                      | nan                   | nan                      | nan                   | nan         | nan
1005646 | Amador Farmers' Market-- Sutter Creek    | Eureka St. & Highway 49     | Sutter Creek | Amador         | California | 95685 | -120.774 | 38.3488 | http://www.amadorfarmersmarket.com                      | nan                                            | nan                             | nan     | nan                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | N     | Y          | Y     | Y    | N     | N    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | Y     | Y      | N      | N      | N         | N       | N             | 3/27/2015 5:50:12 PM  | nan                               | Y      | Y    | N       | Y     | N    | 06/13/2015 to 10/01/2015 | Sat: 9:00 AM-12:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
1002089 | Anderson Happy Valley Farmers Market     | Happy Valley Rd.            | Anderson     | Shasta         | California | 96007 | -122.408 | 40.4487 | nan                                                     | nan                                            | nan                             | nan     | nan                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                        | nan                      | nan                   | nan                      | nan                   | nan         | nan
1006268 | Angels Camp Farmers Market-Fresh Fridays | Utica Park, Utica Lane      | Angels Camp  | Calaveras      | California | 95222 | -120.543 | 38.0722 | http://www.angelscampbusiness.com/events/fresh-fridays/ | nan                                            | nan                             | nan     | nan                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | N     | Y    | N     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | N      | N      | N      | N         | N       | N             | 5/1/2012 11:19:26 AM  | Other                             | N      | Y    | N       | Y     | N    | June to October          | Fri:5:00 PM - 8:00 PM;                     | nan                      | nan                   | nan                      | nan                   | nan         | nan
... (745 rows omitted)

In [ ]:
grader.check("q36")

**Pregunta 4.1.** Cree una tabla de películas estrenadas entre 2010 y 2015 (inclusive) con calificaciones superiores a 8. La tabla solo debe contener las columnas `Title` and `Rating`, **en ese orden**.

Asigne la tabla al nombre `above_eight`.

*Pista:* Piensa en los pasos que debes seguir e intenta ordenarlos en un orden que tenga sentido. ¡Siéntete libre de crear tablas intermedias para cada paso, pero asegúrate de asignar a tu tabla final el nombre "above_eight"!

In [ ]:
import numpy as np
from datascience import *

imdb = Table.read_table('imdb.csv')

# BEGIN SOLUTION NO PROMPT
above_eigh=imdb.where('Rating',are.above_or_equal_to(8)).where('Year',are.between_or_equal_to(2010, 2015))

# END SOLUTION

""" # BEGIN PROMPT
above_eigh= ...
""" # END PROMPT

above_eigh

In [ ]:
grader.check("q41")

**Pregunta 4.2.** Utilice `num_rows` (y aritmética) para encontrar la *el numero* de películas en el conjunto de datos que se estrenaron entre 1900 y 1999, y la *el numero* de películas en el conjunto de datos que se estrenaron en el año 2000 o después.

Asigne "num_en_siglo_20" a el número de películas en el conjunto de datos que se estrenaron entre 1900 y 1999, y "num_en_siglo_21" a el número de películas en el conjunto de datos que se estrenaron en el año 2000 o después.

*Pista:* El *número* de películas estrenadas en el siglo XX es el *número* de películas estrenadas en el siglo XX, dividida por el *número total* de películas.

In [126]:
import numpy as np
from datascience import *

imdb = Table.read_table('imdb.csv')

# BEGIN SOLUTION NO PROMPT

num_movies_in_dataset=imdb.num_rows
num_in_siglo_20=imdb.where('Year',are.between_or_equal_to(1900, 1999))
num_in_21st_century=imdb.where('Year',are.above_or_equal_to(2000))

proportion_in_20th_century=num_in_siglo_20.num_rows/num_movies_in_dataset
proportion_in_21st_century=num_in_21st_century.num_rows/num_movies_in_dataset

# END SOLUTION

""" # BEGIN PROMPT
num_movies_in_dataset = ...
num_in_20th_century = ...
num_in_21st_century = ...
proportion_in_20th_century = ...
proportion_in_21st_century = ...
""" # END PROMPT

proportion_in_20th_century
#proportion_in_21st_century

0.684

In [ ]:
grader.check("q42")

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

These are some submission instructions.

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(run_tests=True)